name: triposg-generator
channels: 
  - defaults 
  - conda-forge 
  - nvidia 

dependencies: 
  - python=3.11
  - pip 
  - cmake=4.0.3
  - cudnn=9.13.1.26
  - gcc=14.2.0
  - gxx=14.2.0
  - gcc_linux-64=14.2.0
  - cuda-toolkit=12.8
  - ninja=1.13.0
